// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: aggregator.proto

package aggregator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentAggregator_GetContent_FullMethodName = "/aggregator.ContentAggregator/GetContent"
)

// ContentAggregatorClient is the client API for ContentAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service
type ContentAggregatorClient interface {
	GetContent(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error)
}

type contentAggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewContentAggregatorClient(cc grpc.ClientConnInterface) ContentAggregatorClient {
	return &contentAggregatorClient{cc}
}

func (c *contentAggregatorClient) GetContent(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentResponse)
	err := c.cc.Invoke(ctx, ContentAggregator_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentAggregatorServer is the server API for ContentAggregator service.
// All implementations must embed UnimplementedContentAggregatorServer
// for forward compatibility.
//
// gRPC service
type ContentAggregatorServer interface {
	GetContent(context.Context, *ContentRequest) (*ContentResponse, error)
	mustEmbedUnimplementedContentAggregatorServer()
}

// UnimplementedContentAggregatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentAggregatorServer struct{}

func (UnimplementedContentAggregatorServer) GetContent(context.Context, *ContentRequest) (*ContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedContentAggregatorServer) mustEmbedUnimplementedContentAggregatorServer() {}
func (UnimplementedContentAggregatorServer) testEmbeddedByValue()                           {}

// UnsafeContentAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentAggregatorServer will
// result in compilation errors.
type UnsafeContentAggregatorServer interface {
	mustEmbedUnimplementedContentAggregatorServer()
}

func RegisterContentAggregatorServer(s grpc.ServiceRegistrar, srv ContentAggregatorServer) {
	// If the following call pancis, it indicates UnimplementedContentAggregatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentAggregator_ServiceDesc, srv)
}

func _ContentAggregator_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentAggregatorServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentAggregator_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentAggregatorServer).GetContent(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentAggregator_ServiceDesc is the grpc.ServiceDesc for ContentAggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentAggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aggregator.ContentAggregator",
	HandlerType: (*ContentAggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContent",
			Handler:    _ContentAggregator_GetContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aggregator.proto",
}
